Temporarily removed Banner
rdai10/zendesk pull request #279
Opened 2021-06-22 21:59 UTC by cole-liferay

Per Zeno's request, removed banner until we can create a new landing page on Pardot.

### Description
Please explain the changes you made.  Include any relevant motivation, context and JIRA tickets.

### Checklist
- [ ] Code compiles without errors.
- [ ] Include tests for new features and functionality.
- [ ] Update README/documentation, when applicable.
- [ ] All tests, new and existing, pass without errors.
- [ ] Checked browser compatibility, especially IE11.

2021-06-22 22:23 UTC, rdai10 requested changes
@cole-liferay can you take a look at my comment and update the change?

2021-06-22 22:23 UTC, rdai10 commented on theme/src/resources/templates/category_pages/liferay_dxp_cloud.hbs
> -			</div>
@cole-liferay I think you want to remove the closing </div> in the next line as well.

2021-06-23 13:14 UTC, cole-liferay reviewed
Removed next line.

2021-06-23 15:50 UTC, rdai10 approved these changes

2021-06-23 15:50 UTC, merged